base_config: ./config/
base_expid: QNN_T26_xDeepFM_iPinYou
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    cin_hidden_units: [[64], [32], [32, 32], [64, 64]]
    num_row: [2, 3, 4]
    num_layers: [4]