base_config: ./config/
base_expid: QNN_T26_DCNv2_ML_1M
dataset_id: ML_1M_7_x1

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    num_heads: [1, 2, 4]
    num_cross_layers: [1, 2, 3]
    num_row: [2, 3, 4, 5]