base_config: ./config/
base_expid: QNN_T26_DCNv2_iPinYou
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    num_cross_layers: [1, 2, 3, 4]
    num_row: [2, 3, 4]
    num_layers: [3, 4]