base_config: ./config/
base_expid: QNN_T26_DeepFM_Frappe
dataset_id: Frappe_x1_h5

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    num_row: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
    num_layers: [2, 3, 4]